package dzikri;

import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
/*
 * Dzikri Alif A
 * dzikrialif99@gmail.com
 * Quiz 2 PBO
 */

/**
 *
 * @author HP
 */
public class FramePembelian extends javax.swing.JFrame {

    private int id = 0;
    private String kode;
    private DefaultTableModel dtmodel;
    private DefaultComboBoxModel dcbModel;
    private ArrayList<Item> belanja = new ArrayList<>();
    
    
    public FramePembelian() {
        Price model = new Price();
        this.dcbModel = new DefaultComboBoxModel<> (model.getNama().toArray());
        
        TabelItem models = new TabelItem();
        this.dtmodel = new DefaultTableModel(models.getNamaKolom(), 0);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelList = new javax.swing.JTable();
        kodeBarangText = new javax.swing.JTextField();
        barangComboBox = new javax.swing.JComboBox<>();
        jumlahBarangText = new javax.swing.JTextField();
        newBUTTON = new javax.swing.JButton();
        addBUTTON = new javax.swing.JButton();
        deleteBUTTON = new javax.swing.JButton();
        saveBUTTON = new javax.swing.JButton();
        cancelBUTTON = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz 2 Pemrograman Berbasis Objek");
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pembelian Barang", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Jenis Barang");

        tabelList.setBackground(new java.awt.Color(153, 204, 255));
        tabelList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Harga Barang", "Jumlah Barang"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelList);

        kodeBarangText.setEnabled(false);

        barangComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang", "Gula", "Kopi", "Susu" }));
        barangComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barangComboBox.setEnabled(false);
        barangComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangComboBoxActionPerformed(evt);
            }
        });

        jumlahBarangText.setToolTipText("");
        jumlahBarangText.setEnabled(false);

        newBUTTON.setText("New");
        newBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBUTTONActionPerformed(evt);
            }
        });

        addBUTTON.setText("Tambah");
        addBUTTON.setEnabled(false);
        addBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBUTTONActionPerformed(evt);
            }
        });

        deleteBUTTON.setText("Hapus");
        deleteBUTTON.setEnabled(false);
        deleteBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBUTTONActionPerformed(evt);
            }
        });

        saveBUTTON.setText("Simpan");
        saveBUTTON.setEnabled(false);
        saveBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBUTTONActionPerformed(evt);
            }
        });

        cancelBUTTON.setText("Cancel");
        cancelBUTTON.setEnabled(false);
        cancelBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(saveBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(barangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jumlahBarangText))
                            .addComponent(kodeBarangText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deleteBUTTON, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(newBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addBUTTON, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kodeBarangText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBUTTON))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(barangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahBarangText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addBUTTON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBUTTON))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBUTTON)
                    .addComponent(cancelBUTTON))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        menuKeluar.setText("Keluar");
        menuKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(menuKeluar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBUTTONActionPerformed
        nonaktif();
    }//GEN-LAST:event_cancelBUTTONActionPerformed
    
    private void newTransaksi(){
        
    }
    
    private boolean isDuplicate(String nama){
        boolean hasil = false;
        ArrayList<String> item = new ArrayList<>();
        for (int i = 0; i < dtmodel.getRowCount(); i++) {
            item.add(dtmodel.getValueAt(i, 0).toString());
        }
        for (String index : item) {
            if (index.equals(nama)) {
                hasil = true;
            }
        }
        return hasil;
    }
    
    private boolean isEmpty(){
        return this.tabelList.getModel().getRowCount() <= 0;
    }
    
    
    private void saveBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBUTTONActionPerformed
        try {
            for (int i = 0; i < dtmodel.getRowCount(); i++) {
                // menyimpan nama barang dan jumlah 
                String nama = dtmodel.getValueAt(i, 0).toString();
                float harga = new Float(dtmodel.getValueAt(i, 1).toString()) ;
                int jumlah  = new Integer(dtmodel.getValueAt(i, 2).toString());
            }
            // instansiasi class Transaksi dengan kode dan comitted belanja
            Transaksi trnsksi = new Transaksi(this.kode, this.belanja);
            StringBuilder sbuilder = new StringBuilder();
            
            sbuilder.append(trnsksi.Pembayaran());
            
            JOptionPane.showMessageDialog(this, sbuilder, "Transaksi", JOptionPane.INFORMATION_MESSAGE);
            newTransaksi();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_saveBUTTONActionPerformed

    private void addBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBUTTONActionPerformed
        
        String nama = this.barangComboBox.getSelectedItem().toString();
        
        int jumlah = new Integer(this.jumlahBarangText.getText());
        
        if (!isDuplicate(nama)) {
            
        } else {
        }
        
    }//GEN-LAST:event_addBUTTONActionPerformed

    private void barangComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangComboBoxActionPerformed
 
        
    }//GEN-LAST:event_barangComboBoxActionPerformed

    private void deleteBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBUTTONActionPerformed
        DefaultTableModel model = (DefaultTableModel)tabelList.getModel();
        model.removeRow(tabelList.getSelectedRow());
    }//GEN-LAST:event_deleteBUTTONActionPerformed

    private void newBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBUTTONActionPerformed
        aktif();
        this.kodeBarangText.setText(this.setKode());
        
    }//GEN-LAST:event_newBUTTONActionPerformed
    public static String now(){
        String DATE_FORMAT_NOW = "yyMMdd";
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT_NOW);
        return sdf.format(cal.getTime());
    
    }
    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        Object option[] = {"Ya", "TIdak"};
        int result = JOptionPane.showOptionDialog(this, 
                "Apakah anda ingin keluar ?", "Konfirmasi", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                null,option,option[1] );
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
            
        }
    }//GEN-LAST:event_menuKeluarActionPerformed
    
    // -- penambahan id / kode barang
    private void tambahkodeId(){
        this.id += 1;
    }
    // -- penambahan id / kode barang
    private void kurangkodeId(){
        this.id -= 1;
    }
    // --
    private String setKode(){
        this.tambahkodeId();
        // -- setting tanggal
        String date = new SimpleDateFormat("yyMMdd").format(new Date());
        this.kode = String.format(date + "%02d", this.id);
        return kode;
    }
    private Object[] addItem(String nama,int jumlah){
        float harga = 0;
        Price item = new Price();
        for (int i = 0; i < item.getNama().size() ; i++) {
            if (nama.equalsIgnoreCase(item.getNama().get(i))) {
                harga = item.getHarga().get(i);
            }
        }
        Object[] objek = { nama,harga,jumlah,};
        return objek;
    }
    
    private void updateJumlah(String nama,int tambah){
        ArrayList<String> item = new ArrayList<>();
        
    }
    
    private void aktif(){
        // enable button & textField
        newBUTTON.setEnabled(false);
        addBUTTON.setEnabled(true);
        deleteBUTTON.setEnabled(true);
        saveBUTTON.setEnabled(true);
        cancelBUTTON.setEnabled(true);
        //-------------------------------------
        jumlahBarangText.setText("1");
        jumlahBarangText.setEnabled(true);
        kodeBarangText.setEnabled(false);
        barangComboBox.setEnabled(true);
    }
    private void nonaktif(){
        // disable button & textField
        newBUTTON.setEnabled(true);
        addBUTTON.setEnabled(false);
        deleteBUTTON.setEnabled(false);
        saveBUTTON.setEnabled(false);
        cancelBUTTON.setEnabled(false);
        //-------------------------------------
        jumlahBarangText.setEnabled(false);
        jumlahBarangText.setText("");
        kodeBarangText.setEnabled(false);
        kodeBarangText.setText("");
        barangComboBox.setEnabled(false);
        barangComboBox.setSelectedIndex(0);
        DefaultTableModel model = (DefaultTableModel) tabelList.getModel();
        while (model.getRowCount() > 0 ) {            
            for (int i = 0; i < model.getRowCount(); i++) {
                model.removeRow(i);
            }
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBUTTON;
    private javax.swing.JComboBox<String> barangComboBox;
    private javax.swing.JButton cancelBUTTON;
    private javax.swing.JButton deleteBUTTON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahBarangText;
    private javax.swing.JTextField kodeBarangText;
    private javax.swing.JMenu menuKeluar;
    private javax.swing.JButton newBUTTON;
    private javax.swing.JButton saveBUTTON;
    private javax.swing.JTable tabelList;
    // End of variables declaration//GEN-END:variables
}
